### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [tvaranka/Noisy_MER#1]
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/72587415/194064875-e5dbddb0-156d-44d0-833e-a36d0b600154.png">
Hello, I got an error when running your program. I think the reason is that there is no data set. Could you please share your data set or teach me how to import the data set for training

**Comment by tvaranka** [comment]
Hey, the experiments use a combined dataset of SMIC, CASME2 and SAMM. You will need to request access to these datasets by the data holders. You can find the links from their corresponding papers

**Comment by YUZHIWANG-bug** [comment]
> Hey, the experiments use a combined dataset of SMIC, CASME2 and SAMM. You will need to request access to these datasets by the data holders. You can find the links from their corresponding papers

Dear author, I am very honored to receive your reply. I have the data set of CASME2, but I do not know how to configure your specific path, If possible, please tell me the specific configuration path or you can update your project, such as where the dataset should be placed, thank you very much!

**Comment by YUZHIWANG-bug** [comment]
> Hey, the experiments use a combined dataset of SMIC, CASME2 and SAMM. You will need to request access to these datasets by the data holders. You can find the links from their corresponding papers

And I would like to say that you are the first author to reply to me, which makes me very excited and really honored。

**Comment by tvaranka** [comment]
Thanks for bringing up the issue. I will add this information to the readme. You can change the path for each of the datasets in the `datasets.py` file. For example, here for casme2.
https://github.com/tvaranka/Noisy_MER/blob/31500970643837213fd8bbafeb30dc9390f6514a/datasets.py#L163

Change both the `df_path`, which refers to the excel file containing metadata and the `dataset_path`, which refers to the cropped dataset root.

I also added a link to the preprocessed optical flow. You can also generate it yourself.

Note, in this paper we only experimented on the composite dataset, hence you will need all three of the datasets to run the code.

Let me know if there any more issues and I will be happy to help

**Comment by YUZHIWANG-bug** [comment]
> Thanks for bringing up the issue. I will add this information to the readme. You can change the path for each of the datasets in the `datasets.py` file. For example, here for casme2.
> 
> https://github.com/tvaranka/Noisy_MER/blob/31500970643837213fd8bbafeb30dc9390f6514a/datasets.py#L163
> 
> Change both the `df_path`, which refers to the excel file containing metadata and the `dataset_path`, which refers to the cropped dataset root.
> 
> I also added a link to the preprocessed optical flow. You can also generate it yourself.
> 
> Note, in this paper we only experimented on the composite dataset, hence you will need all three of the datasets to run the code.
> 
> Let me know if there any more issues and I will be happy to help

Thank you for your reply, it will be very useful to me, thank you very much!

**Comment by YUZHIWANG-bug** [comment]
> Thanks for bringing up the issue. I will add this information to the readme. You can change the path for each of the datasets in the `datasets.py` file. For example, here for casme2.
> 
> https://github.com/tvaranka/Noisy_MER/blob/31500970643837213fd8bbafeb30dc9390f6514a/datasets.py#L163
> 
> Change both the `df_path`, which refers to the excel file containing metadata and the `dataset_path`, which refers to the cropped dataset root.
> 
> I also added a link to the preprocessed optical flow. You can also generate it yourself.
> 
> Note, in this paper we only experimented on the composite dataset, hence you will need all three of the datasets to run the code.
> 
> Let me know if there any more issues and I will be happy to help

Dear author, May I ask you whether the result of your project is to remove the noise in the micro-expression recognition, that is, the result should be a noise image. Then, Can I ask you whether this can be used to identify the micro expression in the image or is this just a preprocessing step.

**Comment by tvaranka** [comment]
The proposed methods are used to handle with noise in the labels, not the images. The code can be used to improve the performance of the recognition step and it does not deal with preprocessing.

**Comment by YUZHIWANG-bug** [comment]
> The proposed methods are used to handle with noise in the labels, not the images. The code can be used to improve the performance of the recognition step and it does not deal with preprocessing.

Oh! I see. Thank you very much for your reply！
